---
title: Obihai Settings
author: 'Roger J. Bos'
date: '2019-04-05'
slug: voip
categories:
  - voip
tags:
  - voip
---

I have been a big fan of Google Voice ever since it started as Grand Central.  I installed an Obi110 device at a relatives house to facilite free calls to and from that location.  Learning VoIP has been a long and confusing journey, but basically you need to know about trunks and dialplans.  A trunk is a service provider and that service provider could be a landline (also referred to as publicly switched telephone network - PSTN) or a VoIP provider.  There is also something called a DID, which stands for direct inward dial.  It is just your phone number.  A dialplan is used to match inbound and outbound calls and route them appropirately.  You never had to worry about this with a landline because you only had one service provider.  The Obi devices has handle either 2 or 4 service providers, so you have to learn how to use dialplans.

One of the best features ofthe Obi devices is the Obitalk portal that allows for remote, browser based, configuration.  The reason I choose the Obi110 for the remote location is so the user can make both local and US calls with the same phone and the dialplan will choose the appropriate trunk.  This setup worked flawlessly for many many years.  Then Google Voice changed its underlying structure and stopped supporting XMPP.  Obihai (now Polycom) also decided to end-of-life (EOL) the Obi1xx series of devices, so they cannot connect to the new version of Google Voice.  The Obi1xx is not dead however, since it can still connect to a regualr SIP (session initiation protocal) server.  So for a time the answer was to use [PBXes](www.pbxes.com) as a SIP server and NAF's GVSIP as the new method to make Google Voice a trunk.  This setup too worked really well, until Google Voice changed their servers again to prevent GVSIP connections.  According to Google Voice only Obi2xx (and certain other Polycom devices) can connect to the Google Voice service.

Below I explain my current setup that allows me to keep the Obi110 working with Google Voice and doesn't violate Google Voice's terms of service.  I have an Obi202 at my house that is capable of four service providers.  I use the first service provider as my home phone line, so the other three went unused.  Here I describe how I configured my Obi202 to provide service to 2 additional Google Voice phone numbers.  This is a specific application of more general and well-written instructions by [Robert Stampfli](https://cboh.org/voip/obi/OBi_As_ITSP.html).

Each Obi device has a unique ID, which an be used to call from one Obi to another Obi.  My Obi110 has an id of 200800100.  We will use that for incoming calls from the US.  Here are the four service providers I have configured on my Obi202:

* SP1 is GV1 (main) home phone line
* SP2 is GV2 linked to an overseas Obi110
* SP3 is GV3 (extra) phone line routed thru pbxes.com
* SP4 is SIP registered to pbxes.org

### Obi202 SIP service - SP1
```
Voice Services > SP1 Service > X_InboundCallRoute                  {ph} (optionally {(Mmaa):aa},{ph})

```
X_InboundCallRoute is the dialplan for the inbound calls that show up to the Obi from service provider 1.  All we need here is the regular setting of {ph} which will ring line 1.  I was going to use the Auto Attendant as an easy way for the Obi110 to make outgoing calls, but I figured out a better way, which I describe below.

### Obi SIP service - SP2
```
Voice Services > SP2 Service > X_InboundCallRoute                  pp(200800100)

```
SP2 is configured with the GV number I want to use on the Obi110.  Since this GV phone number is configured on an Obi202, it is compliance with Google Voice's terms of service.  For outgoing calls I use PBXes.com, but incoming calls are easier.  I can configure the X_InboundCallRoute of my Obi202 to be the address of the Obi110 so that whenever anyone calls the GV2 phone number the Obi110 will ring.  You do this by using pp and the id of the Obi device, so pp(200800100) will ring the Obi110.  Incoming calls to the Obi110 are now complete.

### Obi GV service - SP3
```
Voice Services > SP3 Service > X_InboundCallRoute                  SP4(pbx-Obi202@pbxes.com)

```
GV3 is just a test Google Voice nuber to show that it is possible to handle more than one Google Voice number with this setup.  This SP is optional and you don't need to set it.  Here I am not dialing another Obi directly, but instead routing the call to PBXes.com.  With PBXes.com I set up a sub-pbx with the name Obi202 and *pbx* is the name of my PBXes.com account.  

Next we configure SP4 of the Obi202 to register with the sub-pbx I mentioned above.  This effectively makes the Obi202 an internet telephone service provider (ITSP) for my sub-pbx.   

### Obi SIP service - SP4
```
Service Providers > ITSP Profile D > SIP > ProxyServer             pbxes.org (or 144.76.38.78)
Service Providers > ITSP Profile D > SIP > ProxyServerPort         5060
Service Providers > ITSP Profile D > SIP > RegistrationPeriod      120
Service Providers > ITSP Profile D > SIP > X_SpoofCallerID         checked
Service Providers > ITSP Profile D > SIP > X_NoNonceAuth           checked
Service Providers > ITSP Profile D > General > X_EarlyICEEnableIn  checked

Voice Services > SP4 Service > X_ServProvProfile                   ITSP Profile D
Voice Services > SP4 Service > X_InboundCallRoute                  {SP3}
Voice Services > SP4 Service > X_AcceptsSipFromRegistrarOnly       check
Voice Services > SP4 Service > X_NoRegNoCall                       check
Voice Services > SP4 Service > AuthUserName                        pbx-OBi202
Voice Services > SP4 Service > AuthPassword                        (secret)
Voice Services > SP4 Service > X_EnforceRequestUserID              not checked

```


### Obi User Settings
```
User Defined DititMaps > Map2 > Label         maa
User Defined DititMaps > Map2 > DigitMap      (200800100)

```

### pbxes.com service
```
Sub PBXes > username pbx-Obi202
Sub PBXes > password (secret)

Inbound Routing >

Outbound Routing > Trunk Sequence > SIP/pbx-Obi202
Outbound Routing > Extension > (your extension)

```
